### ISSUE TITLE
BAUserSQLiteDatasource attributes crash.

### ISSUE THREAD

**Issue by tazihosniomar** [BatchLabs/Batch-iOS-SDK#31]
Hello,
I'm facing an issue with the batch SDK,
the app crashes on production with the following stackTrace:

## Logs
Crashed: com.batch.userprofile.queue
EXC_BAD_ACCESS KERN_PROTECTION_FAILURE 0x00000065756c6176

Crashed: com.batch.userprofile.queue:
0  libsqlite3.dylib               0xb5950 sqlite3_sourceid + 1672
1  libsqlite3.dylib               0x43094 sqlite3_log + 103700
2  libsqlite3.dylib               0x4364 sqlite3_vfs_find + 3140
3  libsqlite3.dylib               0xe97fc sqlite3_sourceid + 214324
4  libsqlite3.dylib               0x2bc44 sqlite3_log + 8388
5  libsqlite3.dylib               0xbf94 sqlite3_exec + 11380
6  libsqlite3.dylib               0xa57c sqlite3_exec + 4700
7  libsqlite3.dylib               0x9c48 sqlite3_exec + 2344
8  libsqlite3.dylib               0x98c0 sqlite3_exec + 1440
9  SEPHORA                        0x2a30fc -[BAUserSQLiteDatasource attributes] + 4365725948
10 SEPHORA                        0x2a6ba8 __25-[BAUserDataEditor save:]_block_invoke + 4365740968
11 libdispatch.dylib              0x24b4 _dispatch_call_block_and_release + 32
12 libdispatch.dylib              0x3fdc _dispatch_client_callout + 20
13 libdispatch.dylib              0xb694 _dispatch_lane_serial_drain + 672
14 libdispatch.dylib              0xc1e0 _dispatch_lane_invoke + 384
15 libdispatch.dylib              0x16e10 _dispatch_workloop_worker_thread + 652
16 libsystem_pthread.dylib        0xdf8 _pthread_wqthread + 288
17 libsystem_pthread.dylib        0xb98 start_wqthread + 8

com.apple.main:
com.apple.main-thread
0  CoreFoundation                 0xc1af8 __CFCreateCompactBitmap + 100
1  CoreFoundation                 0xe70f4 _CFCharacterSetInitCopyingSet + 356
2  CoreFoundation                 0xf4054 __CFCharacterSetCreateCopy + 324
3  Foundation                     0x3eab8c StringProtocol.addingPercentEncoding(withAllowedCharacters:) + 100
4  Alamofire                      0x47550 $s9Alamofire11URLEncodingV15queryComponents7fromKey5valueSaySS_SStGSS_yptF + 1740
5  Alamofire                      0x46c7c $s9Alamofire11URLEncodingV5query33_07E29AB6DA2856B846193FCC509DA12DLLySSSDySSypGF + 264
6  Alamofire                      0x46a80 $s9Alamofire11URLEncodingV6encode_4with10Foundation10URLRequestVAA0F11Convertible_p_SDySSypGSgtKF + 1428
7  Alamofire                      0x47a80 $s9Alamofire11URLEncodingVAA17ParameterEncodingA2aDP6encode_4with10Foundation10URLRequestVAA0H11Convertible_p_SDySSypGSgtKFTW + 44
8  Moya                           0x7c94 $s4Moya8EndpointC10urlRequest10Foundation10URLRequestVyKF + 1616
9  Moya                           0xcd5c $s4Moya0A8ProviderC21defaultRequestMapping3for7closureyAA8EndpointC_ys6ResultOy10Foundation10URLRequestVAA0A5ErrorOGXEtFZ + 140
10 SEPHORA                        0x77f51c specialized implicit closure #2 in implicit closure #1 in default argument 1 of MoyaProvider.init(endpointClosure:requestClosure:stubClosure:callbackQueue:session:plugins:trackInflights:) + 579956
11 SEPHORA                        0x77f4fc thunk for @escaping @callee_guaranteed (@guaranteed Endpoint, @unowned @callee_guaranteed (@in_guaranteed Result<URLRequest, MoyaError>) -> ()) -> () + 579924
12 Moya                           0xd818 $s4Moya0A8ProviderC13requestNormal_13callbackQueue8progress10completionAA11Cancellable_px_So17OS_dispatch_queueCSgyAA16ProgressResponseVcSgys6ResultOyAA0N0CAA0A5ErrorOGctF + 1252
13 Moya                           0xbc78 $s4Moya0A8ProviderC7request_13callbackQueue8progress10completionAA11Cancellable_px_So17OS_dispatch_queueCSgyAA16ProgressResponseVcSgys6ResultOyAA0M0CAA0A5ErrorOGctF + 116
14 Moya                           0x133c4 $s7RxSwift8ReactiveV4MoyaAD0D12ProviderTypeRzrlE7request_13callbackQueueAA17PrimitiveSequenceVyAA11SingleTraitOAD8ResponseCG6TargetQz_So17OS_dispatch_queueCSgtFAA10Disposable_pys6ResultOyAMs5Error_pGccfU_ + 236
15 RxSwift                        0x6ea94 $s7RxSwift21PrimitiveSequenceTypePA2A11SingleTraitO0G0RtzrlE6create9subscribeAA0cD0VyAE7ElementQzGAA10Disposable_pys6ResultOyAMs5Error_pGcc_tFZAaO_pAA11AnyObserverVyAMGcfU_TA + 104
16 RxSwift                        0x2d308 $s7RxSwift19AnonymousObservable33_95EBF5692819D58425EC2DD0512D115ALLC3run_6cancelAA10Disposable_p4sink_AaG_p12subscriptiontqd___AA10Cancelable_pt7ElementQyd__RszAA12ObserverTypeRd__lF + 240
17 RxSwift                        0x5a1cc $s7RxSwift8ProducerC9subscribeyAA10Disposable_pqd__7ElementQyd__RszAA12ObserverTypeRd__lF + 284
18 RxSwift                        0x4d690 $s7RxSwift9MergeSink33_DDEA0423368B3B462AE46699A4D080E1LLC3runyAA10Disposable_pAA10ObservableCyxGF + 332
19 RxSwift                        0x4e430 $s7RxSwift7FlatMap33_DDEA0423368B3B462AE46699A4D080E1LLC3run_6cancelAA10Disposable_p4sink_AaG_p12subscriptiontqd___AA10Cancelable_ptAA12ObserverTypeRd__7ElementQyd__ALRt_lFTm + 228
20 RxSwift                        0x5a1cc $s7RxSwift8ProducerC9subscribeyAA10Disposable_pqd__7ElementQyd__RszAA12ObserverTypeRd__lF + 284
21 RxSwift                        0x7e250 $s7RxSwift11TimeoutSink33_9F6F114FFA256787F41DE270EB9B006FLLC3runAA10Disposable_pyF + 240
22 RxSwift                        0x7eac0 $s7RxSwift7Timeout33_9F6F114FFA256787F41DE270EB9B006FLLC3run_6cancelAA10Disposable_p4sink_AaG_p12subscriptiontqd___AA10Cancelable_pt7ElementQyd__RszAA12ObserverTypeRd__lF + 204
23 RxSwift                        0x5a1cc $s7RxSwift8ProducerC9subscribeyAA10Disposable_pqd__7ElementQyd__RszAA12ObserverTypeRd__lF + 284
24 RxSwift                        0x48890 $s7RxSwift3Map33_5428EFA9A9B0C0340021B871D2E5AC01LLC3run_6cancelAA10Disposable_p4sink_AaG_p12subscriptiontqd___AA10Cancelable_pt7ElementQyd__Rs_AA12ObserverTypeRd__lF + 252
25 RxSwift                        0x5acb4 $s7RxSwift8ProducerC9subscribeyAA10Disposable_pqd__7ElementQyd__RszAA12ObserverTypeRd__lFAaE_pyt_tcfU_ + 228
26 RxSwift                        0x5a3a0 $s7RxSwift22CurrentThreadSchedulerC8schedule_6actionAA10Disposable_px_AaF_pxctlFyt_Tg5 + 168
27 RxSwift                        0x5a2a0 $s7RxSwift8ProducerC9subscribeyAA10Disposable_pqd__7ElementQyd__RszAA12ObserverTypeRd__lF + 496
28 RxSwift                        0x52000 $s7RxSwift14ObservableTypePAAE9subscribeyAA10Disposable_pyAA5EventOy7ElementQzGcF + 240
29 RxSwift                        0x6ede8 $s7RxSwift21PrimitiveSequenceTypePA2A11SingleTraitO0G0RtzrlE9subscribeyAA10Disposable_pys6ResultOy7ElementQzs5Error_pGcF + 292
30 RxSwift                        0x6f3e4 $s7RxSwift21PrimitiveSequenceTypePA2A11SingleTraitO0G0RtzrlE9subscribe9onSuccess0I7Failure0I8DisposedAA10Disposable_py7ElementQzcSg_ys5Error_pcSgyycSgtF + 652
31 SEPHORA                        0x7bbe88 specialized AnalyticsProvider.trackRealtimeOrderConfirmation(order:basket:productItems:) + 828128
32 SEPHORA                        0x7b7710 CheckoutStepsViewModel.trackOrderConfirmationEvent() + 809832
33 SEPHORA                        0x7b66b8 CheckoutStepsViewModel.orderPlaced() + 805648
34 SEPHORA                        0x7b89cc protocol witness for CheckoutStepsViewModeling.orderPlaced() in conformance CheckoutStepsViewModel + 814628
35 SEPHORA                        0xab894 CheckoutStepsViewController.performAction(name:params:completionHandler:) + 222 (CheckoutStepsViewController.swift:222)
36 SEPHORA                        0xde68 closure #1 in APIManager.performAction(name:params:completionHandler:) + 4363017832 (<compiler-generated>:4363017832)
37 SEPHORA                        0xf2b7c thunk for @escaping @callee_guaranteed () -> () + 4363955068 (<compiler-generated>:4363955068)
38 libdispatch.dylib              0x24b4 _dispatch_call_block_and_release + 32
39 libdispatch.dylib              0x3fdc _dispatch_client_callout + 20
40 libdispatch.dylib              0x127f4 _dispatch_main_queue_drain + 928
41 libdispatch.dylib              0x12444 _dispatch_main_queue_callback_4CF + 44
42 CoreFoundation                 0x9aa08 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
43 CoreFoundation                 0x7c368 __CFRunLoopRun + 2036
44 CoreFoundation                 0x811e4 CFRunLoopRunSpecific + 612
45 GraphicsServices               0x1368 GSEventRunModal + 164
46 UIKitCore                      0x3a2d88 -[UIApplication _run] + 888
47 UIKitCore                      0x3a29ec UIApplicationMain + 340
48 SEPHORA                        0x8500 main + 4362994944 (<compiler-generated>:4362994944)
49 ???                            0x1de839948 (Missing)

### SDK Version
1.19.2
### Installation method
cocoapods
### Relevant development tools versions
Xcode 13.4

----------------------------- 

Thanks in advance.

Regards.

Omar.

**Comment by abarisain** [comment]
Hi,

Thanks for the report, we will look at it ASAP.

Do you have any information on which iOS versions this happens?

**Comment by abarisain** [comment]
Oh, I forgot, we're tracking this internally as ticket number 48996.

Any information (crash rate, devices, iOS versions, your SPM/cocoapods dependencies) would help us a lot: you can send this on our support if you don't want them to be public on GitHub.

Thanks!

**Comment by tazihosniomar** [comment]
Hello @abarisain,

It happens in iOS : 14, 15, 16.
This issue has 175 crash events affecting 174 users in the las 90 days.

Regards.

Omar.

**Comment by abarisain** [comment]
Thanks

**Comment by tazihosniomar** [comment]
Hello @abarisain ,

Data Protection features is not used on our side.

Thanks.

Omar.

**Comment by abarisain** [comment]
Thanks.

We are actively looking but have no answer yet: as the crash happens deep in the SQLite stack, it is hard to pinpoint what is causing it. We didn't manage to reproduce it on our side yet, nor did we get any other report of it happening.

**Comment by abarisain** [comment]
Hello,

We spent a lot of time looking at your app's binary and frameworks and our SDK source, but we couldn't find the reason for the crash.
We did not notice it first hand (as it appears to crash after a successful checkout) nor can we reproduce it on our sample app.

Here's a quick list of what we tried/made sure of:
- Stress testing the event tracker and user data editor from multiple threads
- Forcing sqlite3_shutdown()
- Adding Dynatrace and Firebase to our sample app
- Adding dispatch_assert_queue assertions to make sure that we only ever use a single thread to access sqlite
- Ran static analysis (that we run while developing, but we double checked it)

All of this has been ran both on a simulator (with TSAN enabled) and a physical iPhone 14 Pro.

We did find a couple of things we could improve on our end (using sqlite3_open_v2 rather than sqlite3_open, initializing the DB on the shared queue) but those would not fix your issue.

Our guess is that your app is experiencing memory corruption. It's hard to prove as it is most likely random.
Why do we suspect that?
Three things about the crash stand out:
- `KERN_PROTECTION_FAILURE` : this means that a pointer is widly invalid and ends up in protected memory. This is not a "use after free" issue, which more commonly happens
- The crash is deep in sqlite3's code, not at an entry point
- According to the stack trace, `-[BAUserSQLiteDatasource attributes]` calls `sqlite3_exec`, which is not a call that we make in this method: https://github.com/BatchLabs/Batch-iOS-SDK/blob/master/Sources/Batch/Modules/User/BAUserSQLiteDatasource.m#L350-L360 . I tried corrupting the ivars on purpose, and my stack trace shows sqlite3_ste

Now, it's entirely possible that Batch's code could mess up a pointer, but this usually ends up with a `KERN_INVALID_ADDRESS`. Also, we write the `_database` ivar only once and the other ones are local variables. Still, we do not rule this out and will be on the lookout for any other report of problems with our sqlite code while continuing to run static analysis.

The next step on your end would be to:
- Look at your other crashes and see if there are some other ones that can't really be explained
- Look at the other events that crashlytics grouped under this one. Are they different?
- Try to reproduce this locally. Maybe there is a way to do whatever `AnalyticsProvider.trackRealtimeOrderConfirmation()` does to crash the app in a reproductible way: that would help a lot.
- Run your app under TSAN https://www.avanderlee.com/swift/thread-sanitizer-data-races/ , making sure that `AnalyticsProvider.trackRealtimeOrderConfirmation()`  is called as TSAN audits at run time

We'll keep this issue open a little while.

Have a nice day,
Arnaud
